name: helm-upgrade


run-name: ${{ github.actor }} - ${{ github.ref_name }}


on:
 workflow_call:
   inputs:
     environment:
       required: true
       description: 'Environment to deploy to'
       type: string
     version:
       required: true
       description: 'Version of the image to deploy'
       type: string
     helm-values-path:
       description: 'Path to the helm values file'
       type: string
       default: './todoapp/values.yaml'
     helm-release-name:
       description: 'Name of the helm release'
       type: string
       default: todoapp
jobs:
 deploy-helm:
   runs-on: ubuntu-latest
   environment: ${{ inputs.environment }}
   name: ${{ inputs.environment }}


   steps:
   - uses: actions/download-artifact@v4
     with:
       name: helm-package
       path: .


   - uses: actions/download-artifact@v4
     with:
       name: helm-artifacts
       path: .


   - name: Set up Helm
     uses: azure/setup-helm@v4.2.0


   - uses: azure/setup-kubectl@v4
     name: Set up Kubectl


   - uses: azure/login@v2

     with:
       creds: ${{ secrets.AZURE_CREDENTIALS }}


   - uses: azure/aks-set-context@v3

     with:
       cluster-name: ${{ vars.AZURE_CLUSTER_NAME }}
       resource-group: ${{ vars.AZURE_RESOURCE_GROUP }}



   - name: Deploy Helm
     run: |
       helm upgrade --install --atomic  --wait --timeout 1800s --debug ${{ inputs.helm-release-name }} ./todoapp-*.tgz  \
         -f ${{ inputs.helm-values-path }} \
         --set mysql.configs.MYSQL_ROOT_PASSWORD="${{ secrets.MYSQL_ROOT_PASSWORD }}" \
         --set mysql.configs.MYSQL_USER="${{ secrets.MYSQL_USER }}" \
         --set mysql.configs.MYSQL_PASSWORD="${{ secrets.MYSQL_PASSWORD }}" \
         --set todoapp.secrets.password="${{ secrets.TODOAPP_PASSWORD }}" \
         --set todoapp.secrets.login="${{ secrets.TODOAPP_LOGIN }}" \
         --set todoapp.secrets.DB_CONNECTION="${{ secrets.DB_CONNECTION }}" \
         --set global.environment="${{ inputs.environment }}" \
         --set todoapp.image.version="${{ inputs.version }}"
